# Generated by Django 3.2.10 on 2022-02-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_order_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_cost",
        ),
    ]
